Repository kkn1125/mkDocumentifyJS, pull requests merged in 2021-11, with the labels that each got.

#51 Oho update 3
  dist/assets/css/chat.css
  dist/assets/js/theme.js
Labels: enhancement

#53 v024 update list
  README.md
  UPDATE.md
  dist/assets/css/chat.css
  dist/assets/css/gnb.css
  dist/assets/css/main.css
  dist/assets/js/documentify.js
  dist/assets/js/example.js
  dist/assets/js/theme.js
  dist/data/userData.json
  dist/include/chat-popup.html
  dist/include/footer.html
  dist/include/updates.html
Labels: bug, enhancement

#54 search bar 검색어 출력 수정
  dist/assets/css/gnb.css
  dist/assets/js/theme.js
  dist/include/global_nav_bar.html
Labels: enhancement

#55 update readme.md
  README.md
Labels: documentation

#58 사이드바 반응형, 채팅창 반응형 및 메일기능 연결
  UPDATE.md
  dist/assets/css/chat.css
  dist/assets/css/gnb.css
  dist/assets/css/main.css
  dist/assets/js/theme.js
  dist/include/headBundle.html
  dist/include/scriptBundle.html
Labels: bug, enhancement

#59 버그수정
  README.md
  UPDATE.md
  dist/assets/css/chat.css
  dist/assets/css/gnb.css
  dist/assets/css/main.css
  dist/assets/js/documentify.js
  dist/assets/js/example.js
  dist/assets/js/theme.js
  dist/data/userData.json
  dist/include/updates.html
Labels: bug

#61 main 브랜치 검토 리퀘스트
  dist/assets/css/gnb.css
  dist/assets/js/theme.js
  dist/include/global_nav_bar.html
Labels: invalid

#64 이슈 변경사항 일부 적용
  dist/assets/css/gnb.css
  dist/assets/css/main.css
  dist/assets/js/documentify.js
  dist/assets/js/theme.js
  dist/include/origin-lines-per.html
  dist/include/origin-lines.html
  dist/include/side-nav-bar.html
Labels: bug, enhancement

#66 Oho update 6
  dist/assets/css/gnb.css
  dist/assets/js/theme.js
Labels: enhancement

#69 sync
  package.json
Labels: sync
