Repository kkn1125/mkDocumentifyJS, pull requests merged in 2022-04, with the labels that each got.

#71 update
  assets/__tests__/core.js
  assets/__tests__/methods.js
  assets/__tests__/methods.test.js
  index.html
Labels: update

#73 태그 대수정
  assets/__tests__/BreakParagraph.js
  assets/__tests__/BreakParagraph.test.js
  assets/__tests__/__comments/a.js
  assets/__tests__/__comments/b.js
  assets/__tests__/__comments/origin.js
  assets/__tests__/__comments/sample.js
  assets/__tests__/methods.js
  assets/__tests__/methods.test.js
  assets/__tests__/source.js
  assets/src/css/main.css
  assets/src/scripts/core.js
  index.html
  package.json
Labels: enhancement

#74 Develop
  assets/__tests__/BreakParagraph.js
  assets/__tests__/BreakParagraph.test.js
  assets/__tests__/__comments/a.js
  assets/__tests__/__comments/b.js
  assets/__tests__/__comments/origin.js
  assets/__tests__/__comments/sample.js
  assets/__tests__/methods.js
  assets/__tests__/methods.test.js
  assets/__tests__/source.js
  assets/src/css/main.css
  assets/src/scripts/core.js
  index.html
  package.json
Labels: enhancement

#75 tag별 regex매칭 및 constructor function 완성
  assets/__tests__/oho.js
  assets/__tests__/oho.test.js
  package-lock.json
  package.json
Labels: sync

#76 ohoraming test code merging & refactoring
  README.md
  assets/__tests__/BreakParagraph.js
  assets/__tests__/BreakParagraph.test.js
  assets/__tests__/__comments/sample.js
  assets/__tests__/oho.js
  assets/__tests__/oho.test.js
  assets/__tests__/source.js
  assets/__tests__/source.test.js
Labels: bug, enhancement, sync, update

#77 Develop
  README.md
  assets/__tests__/BreakParagraph.js
  assets/__tests__/BreakParagraph.test.js
  assets/__tests__/__comments/sample.js
  assets/__tests__/oho.js
  assets/__tests__/oho.test.js
  assets/__tests__/source.js
  assets/__tests__/source.test.js
  package-lock.json
  package.json
Labels: bug, enhancement, sync, update

#83 내용 확인, 수정 반영
  assets/__tests__/__comments/sample.js
  assets/__tests__/source.test.js
  assets/src/parser/core.js
  assets/src/parser/source.js
  assets/src/scripts/main.js
  assets/src/templates/function.js
  assets/src/templates/param.js
  index.html
Labels: enhancement

#84 Develop
  assets/__tests__/__comments/sample.js
  assets/__tests__/source.test.js
  assets/src/parser/core.js
  assets/src/parser/source.js
  assets/src/scripts/main.js
  assets/src/templates/function.js
  assets/src/templates/param.js
  index.html
Labels: enhancement

#85 desc, info, member card 완성
  assets/__tests__/__comments/sample.js
  assets/src/parser/source.js
  assets/src/templates/desc.js
  assets/src/templates/info.js
  assets/src/templates/member.js
Labels: update

#86 member type, returns card 완료
  assets/src/parser/source.js
  assets/src/scripts/main.js
  assets/src/templates/function.js
  assets/src/templates/member.js
  assets/src/templates/returns.js
Labels: enhancement

#87 Develop
  assets/__tests__/__comments/sample.js
  assets/src/parser/source.js
  assets/src/scripts/main.js
  assets/src/templates/desc.js
  assets/src/templates/function.js
  assets/src/templates/info.js
  assets/src/templates/member.js
  assets/src/templates/returns.js
Labels: enhancement

#88 브랜치 병합 완료
  assets/src/parser/source.js
  assets/src/scripts/main.js
  assets/src/templates/desc.js
  assets/src/templates/function.js
  assets/src/templates/info.js
  assets/src/templates/member.js
  assets/src/templates/param.js
Labels: enhancement

#89 Develop
  assets/src/parser/source.js
  assets/src/scripts/main.js
  assets/src/templates/desc.js
  assets/src/templates/function.js
  assets/src/templates/info.js
  assets/src/templates/member.js
  assets/src/templates/param.js
Labels: enhancement

#91 후처리 버그로 코드 전체 수정
  assets/__tests__/BreakParagraph.js
  assets/__tests__/BreakParagraph.test.js
  assets/__tests__/__comments/sample.js
  assets/__tests__/oho.js
  assets/__tests__/oho.test.js
  assets/__tests__/source.test.js
  assets/src/parser/source.js
  assets/src/scripts/main.js
  assets/src/templates/desc.js
  assets/src/templates/function.js
  assets/src/templates/info.js
  assets/src/templates/member.js
  assets/src/templates/param.js
  assets/src/templates/returns.js
  index.html
Labels: bug, enhancement, sync, update, review

#92 Develop
  assets/__tests__/BreakParagraph.js
  assets/__tests__/BreakParagraph.test.js
  assets/__tests__/__comments/sample.js
  assets/__tests__/oho.js
  assets/__tests__/oho.test.js
  assets/__tests__/source.test.js
  assets/src/parser/source.js
  assets/src/scripts/main.js
  assets/src/templates/desc.js
  assets/src/templates/function.js
  assets/src/templates/info.js
  assets/src/templates/member.js
  assets/src/templates/param.js
  assets/src/templates/returns.js
  index.html
Labels: bug, enhancement, sync, update, review
